name: Elixir Cache
description: Elixir Cache
runs:
  using: "composite"
  steps:
    - uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
      with:
        path: '**/deps'
        key: cache-elixir-${{ github.workflow }}-${{ github.job }}-ghcr.io/ockam-network/ockam/builder@sha256:ea810e06304a0178a8716060033524ff92dfce2d51c9b6dbc17305d11e967851-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          cache-elixir-${{ github.workflow }}-${{ github.job }}-ghcr.io/ockam-network/ockam/builder@sha256:ea810e06304a0178a8716060033524ff92dfce2d51c9b6dbc17305d11e967851-
